about/urls.py
from django.urls import re_path , include , path
from . import views

app_name = "about"
urlpatterns = [
    path('', views.home, name='home'),
    path('news', views.news, name='news'),
    path('service/ticket', views.s_ticket, name='se_ticket'),
    path('service/shop', views.s_shop, name='se_shop'),
    path('service/regi', views.s_regi, name='se_regi'),
    path('service/market', views.s_market, name='se_market'),
    path('support/guide', views.guide, name='guide'),
    path('support/contact', views.contact, name='contact'),
    path('support/faq', views.faq, name='faq'),
    path('support/about', views.about, name='about'),
    path('document/terms', views.terms, name='terms'),
    path('document/privacy', views.privacy, name='privacy'),
]

news/urls.py
from django.urls import re_path , include , path
from django.contrib.auth import views as auth_views
from . import views

app_name ="news"
urlpatterns = [
    path('detail/<int:id>', views.detail, name='detail'),
]

nosta/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.contrib.auth import views as auth_views
from django.views.static import serve 
from django.conf import settings
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_control

urlpatterns = [
    path('system/admin/', admin.site.urls),
    path('', include('top.urls')),
    path('shop/', include('shop.urls')),
    path('app/', include('userapp.urls')),
    path('market/', include('market.urls')),
    path('regi/', include('regi.urls')),
    path('ticket/', include('ticket.urls')),
    path('auth/', include('appauth.urls')),
    path('news/',include('news.urls')),
    path('about/', include('about.urls')),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('accounts/password_change_form/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change_form'),
    path('accounts/password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_finish.html'), name='password_change_done'),
    path('accounts/password_reset_form/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),    # 追加
    path('accounts/password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_mail_done.html'), name='password_reset_done'),    # 追加
    path('accounts/password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirmation.html'), name='password_reset_confirm'),    # 追加
    path('accounts/password_reset_finish/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_finish.html'), name='password_reset_complete'),    # 追加
]

top/urls.py
from django.urls import re_path , include , path
from . import views

app_name = "top"
urlpatterns = [
    path('', views.top, name='index'),
    ## Search is not view but also api.
    path('/search',views.search,name="search")
]

about/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from db.models import *
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.html import strip_tags

# Create your views here.
def home(request):
    news = News.objects.all().filter(channel="all").order_by('created_at').reverse()
    return render(request,'about/top.html',{
        'news':news,
    })

def news(request):
    news = News.objects.all().order_by('created_at').reverse()
    return render(request,'about/news.html',{
        'news':news,
    })

def s_ticket(request):
    return render(request,'about/service/ticket.html',{
    })

def s_shop(request):
    return render(request,'about/service/shop.html',{
    })

def s_regi(request):
    return render(request,'about/service/regi.html',{
    })

def s_market(request):
    return render(request,'about/service/market.html',{
    })
def guide(request):
    return HttpResponse("準備中...")

def faq(request):
    general = FAQ.objects.all().filter(category="general")
    ticket = FAQ.objects.all().filter(category="ticket")
    shop = FAQ.objects.all().filter(category="shop")
    regi = FAQ.objects.all().filter(category="regi")
    market = FAQ.objects.all().filter(category="market")
    other = FAQ.objects.all().filter(category="other")
    return render(request,'about/support/faq.html',{
        'general':general,
        'ticket':ticket,
        'shop':shop,
        'regi':regi,
        'market':market,
        'other':other
    })

def about(request):
    return HttpResponse("準備中...")

def contact(request):
    if request.method == "POST":
        context = {
            "orgname":request.POST["org"],
            "username":request.POST["name"],
            "mail": request.POST["email"],
            "content": request.POST["content"]
        }
        subject = "お問い合わせいただきありがとうございます"
        message = strip_tags(render_to_string('mail/contact.html', context))
        from_email = "no-reply@nosta.prasic-plus.com"
        recipient_list =[request.POST["email"]]
        bcc = ["nostacs@gmail.com"]
        msg = EmailMessage(subject, message, from_email, recipient_list, bcc)
        msg.send()
        return render(request,'about/support/send.html')
    else:
        return render(request,'about/support/contact.html')

def terms(request):
    return render(request,'about/support/term.html')
    
def privacy(request):
    return render(request,'about/support/policy.html')

news/views.py
from django.shortcuts import render
from db.models import *

# Create your views here.
def detail(request,id):
    news = News.objects.get(id=id)
    return render(request,'news/detail.html',{
        'news':news
        })

top/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from db.models import *
from django.db.models import *
from django.db.models.functions import *
from django.template.loader import render_to_string

# Create your views here.
def top(requests):
    shops = Shop.objects.filter(market_active=True).annotate(fav=Count('favorites')).order_by('fav')
    return render(requests,'top/index.html',{'shops':shops})
def search(requests):
    key = requests.POST["key"]
    shops = Shop.objects.filter(Q(market_active=True)&(Q(name__icontains=key)|Q(description__icontains=key))).annotate(fav=Count('favorites')).order_by('fav')
    data = render_to_string('top/search.html',{
        'shops':shops
    })
    return HttpResponse(data)

templates/about/news.html
{% extends 'page_base.html' %}{% load static %}{% block content %}
<section>
    <div class="hero">
        <!-- Hero content: will be in the middle -->
        <div class="hero-body" style="min-height: 300px; background-color: #00517c; color: azure; vertical-align: middle; vertical-align: middle">
            <div class="container my-2" id="start">
                <h1 class="has-text-centered p-6" style="font-size: min(8vw, 3rem)">NEWS</h1>
            </div>
        </div>
        <div class="hero-foot">
            <nav class="breadcrumb mx-3  my-1" aria-label="breadcrumbs">
                <ul>
                    <li><a class="is-size-6 mx-1" href="{% url 'about:home' %}" aria-current="page"  style="color: #00517c">トップ</a></li>
                    <li><a class="is-size-6 mx-1" href="#" aria-current="page"  style="color: #323232">ニュース</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="container mt-6 p-4" id="news">
        <div class="container box p-4">
            {% if news.count == 0 %}
            <p class="hero hero-body subtitle">配信されているおしらせはありません</p>
            {% endif %} {% for content in news %}
            <div class="m-1 columns" style="width: 100%">
                <a href="{% url 'news:detail' content.id %}" style="color: dimgray; display: inline; width: 100%">
                    <c class="column is-3" style="display: inline-block">{{ content.updated_at |date:"Y/m/d" }}</c>
                    <c class="column is-2" style="display: inline-block"><span class="tag is-link is-light">{{ content.tag }}</span></c></c>
                    <c class="column is-5" style="display: inline-block">{{ content.title }}</c>
                    <c class="column is-1" style="display: inline-block"><span class="dli-chevron-right"></span></c>
                </a>
            </div>
            <hr />
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

templates/about/top.html
{% extends 'page_base.html' %}{% load static %}{% block content %}
<section>
    <div class="hero">
        <!-- Hero content: will be in the middle -->
        <div class="hero-body" style="min-height: 300px; background-color: #00517c; color: azure; vertical-align: middle; vertical-align: middle">
            <div class="container my-2" id="start">
                <h1 class="has-text-centered p-6" style="font-size: min(8vw, 3rem)">NOSTAをはじめよう</h1>
                <div class="p-4 has-text-centered" style="font-size: min(4.5vw, 1.5rem)">
                    <p>NOSTAは簡単なセットアップで即戦力になる店舗運営支援ツールです</p>
                    <p>文化祭の模擬店から大規模店舗まで場所<c style="font-size: 10px">※１</c>や規模に縛られないサービスを提供します</p>
                    <p class="m-6 help">※１ インターネットに接続できる端末が必要です</p>
                </div>
                <div class="columns">
                    <div class="column m-2">
                        <div class="has-text-centered">
                            <p class="is-size-6"><b>NOSTA IDをお持ちの方はこちら</b></p>
                            <a href="{% url 'login' %}" class="button is-info is-light m-4">NOSTA IDでログイン</a>
                        </div>
                    </div>
                    <div class="column m-2">
                        <div class="has-text-centered">
                            <p class="is-size-6"><b>NOSTA IDの新規登録はこちら</b></p>
                            <a href="{% url 'register' %}" class="button is-info is-light m-4">NOSTA IDを新規登録</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hero footer: will stick at the bottom -->
        <div class="hero-foot is-hidden-mobile">
            <nav class="tabs is-boxed is-fullwidth">
                <div class="container">
                    <ul>
                        <li>
                            <a href="#about">NOSTAのサービス</a>
                        </li>
                        <li>
                            <a href="#charge">ご利用料金</a>
                        </li>
                        <li>
                            <a href="#model-case">活用法</a>
                        </li>
                        <li>
                            <a href="#support">サポート</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <div class="container mt-6" id="news">
        <div class="container box p-4" style="min-height: 20vh">
            <strong class="m-2" style="color: #00517c">重要なおしらせ</strong>
            {% if news.count == 0 %}
                <p class="hero hero-body subtitle">
                    配信されているおしらせはありません
                </p>
            {% endif %}
            {% for content in news %}
            <div class="m-1 columns" style="width: 100%">
                <a href="{% url 'news:detail' content.id %}" style="color: dimgray; display: inline; width: 100%">
                    <c class="column is-3" style="display: inline-block">{{ content.created_at |date:"Y/m/d" }}</c>
                    <c class="column is-2" style="display: inline-block"><span class="tag is-link is-light">{{ content.tag }}</span></c>
                    <c class="column is-5" style="display: inline-block">{{ content.title }}</c>
                    <c class="column is-1" style="display: inline-block"><span class="dli-chevron-right"></span></c>
                </a>
            </div>
            <hr />
            {% endfor %}
            <div class="has-text-centered"><a class="button is-light is-info"  href="{% url 'about:news' %}">ニュース一覧を見る</a></div>
        </div>
    </div>
    <div class="container my-4" id="about">
        <h3 class="has-text-centered my-6" style="font-size: min(10vw, 3rem)">NOSTAのサービス</h3>
        <div class="columns m-2">
            <div class="column is-3">
                <div style="display: block; margin: auto">
                    <img src="{% static 'image/logo_ticket.png' %}" style="max-height: 10rem" />
                </div>
            </div>
            <div class="column is-9">
                <h3 class="is-size-4"><strong>整理券の最適解</strong></h3>
                <hr />
                <p>シンプルなUIで簡単操作</p>
                <p>店舗ディスプレイ向けの画面やダッシュボードも完備</p>
                <div class="mt-3"></div>
                <a href="{% url 'about:se_ticket' %}" class="button is-light is-gray">さらに詳しく</a>
            </div>
        </div>
        <div class="columns m-2">
            <div class="column is-3">
                <div style="display: block; margin: auto">
                    <img src="{% static 'image/logo_shop.png' %}" style="max-height: 10rem" />
                </div>
            </div>
            <div class="column is-9">
                <h3><strong class="is-size-4">店舗をとことんサポート</strong></h3>
                <hr />
                <p>NOSTAのサービスを１つの画面で管理可能</p>
                <p>リアルタイムの確認から分析まで</p>
                <div class="mt-3"></div>
                <a href="{% url 'about:se_ticket' %}" class="button is-light is-gray">さらに詳しく</a>
            </div>
        </div>
        <div class="columns m-2">
            <div class="column is-3">
                <div  style="display: block; margin: auto;">
                <img src="{% static 'image/logo_regi.png' %}" style="max-height: 10rem;">
                </div>
            </div>
            <div class="column is-9">
                <h3><strong class="is-size-4">見やすい画面で簡単会計</strong></h3>
                <hr>
                <p>店舗での会計からオンライン注文の会計までwebアプリで完結</p>
                <p>予約情報から在庫情報までアプリで簡単照会</p>
                <div class="mt-3"></div>
                <a href="{% url 'about:se_regi' %}" class="button is-light is-gray">さらに詳しく</a>
            </div>
        </div>
        <div class="columns m-2">
            <div class="column is-3">
                <div  style="display: block; margin: auto;">
                <img src="{% static 'image/logo_market.png' %}" style="max-height: 10rem;">
                </div>
            </div>
            <div class="column is-9">
                <h3><strong class="is-size-4">オンラインでも自分のお店を</strong></h3>
                <hr>
                <p>店舗の在庫とオンラインの在庫をまとめて管理可能</p>
                <div class="mt-3"></div>
                <a href="{% url 'about:se_regi' %}" class="button is-light is-gray">さらに詳しく</a>
            </div>
        </div>
    </div>
    <div class="container my-4" id="charge">
        <h3 class="has-text-centered my-6" style="font-size: min(8vw, 3rem)">料金プラン</h3>
        <p class="help has-text-centered">アカウントのアップグレードはNOSTA SHOPの設定画面より行うことが可能です</p>
        <div class="columns m-3">
            <div class="column" style="min-height: 30vh">
                <div class="has-text-centered" style="font-size: min(5vw, 1.5rem)">Liteプラン</div>
                <hr />
                <strong>月額料金：￥０/店舗</strong>
                <p>NOSTAを手軽に始められるプラン</p>
                <div class="mt-6"></div>
                <ul>
                    <li>NOSTA TICKETのすべての機能</li>
                    <li>NOSTA REGIのすべての機能</li>
                    <li>ユーザー管理機能</li>
                    <li>在庫管理機能</li>
                    <li>伝票管理機能</li>
                    <li>分析機能</li>
                </ul>
                <p class="mt-3">詳細については各機能の紹介ページをご覧ください</p>
            </div>
            <div class="column" style="min-height: 30vh;">
                <div class="has-text-centered" style="font-size: min(5vw,1.5rem);">
                    Plusプラン
                </div>
                <hr/>
                <!--<strong>月額基本料金：￥500/店舗</strong>-->
                <strong>現在、招待制で提供しています</strong>
                <p>NOSTAの機能をほぼすべて使えるプラン</p>
                <div class="mt-6"></div>
                <ul>
                    <li>NOSTA TICKETのすべての機能</li>
                    <li>NOSTA REGIのすべての機能</li>
                    <li>ユーザー管理機能</li>
                    <li>在庫管理機能</li>
                    <li>伝票管理機能</li>
                    <li>分析機能</li>
                    <li>オンライン注文機能</li>
                    <li>API連携機能</li>
                    <li>外部連携機能</li>
                </ul>
                <p class="mt-3">詳細については各機能の紹介ページをご覧ください</p>
            </div>
            <!--
            <div class="column" style="min-height: 30vh;">
                <div class="has-text-centered" style="font-size: min(5vw,1.5rem);">
                    Premiumプラン
                </div>
                <hr/>
                <strong>月額基本料金：￥2000/組織</strong>
                <p class="help">Premiumプランでは店舗あたりではなく組織あたりの料金となります</p>
                <p>Basic,Liteプランに加えてオンライン注文までフルサポート</p>
                <p>文化祭や模擬店にもおすすめなプラン</p>
                <div class="mt-6"></div>
                <ul>
                    <li>NOSTA TICKETのすべての機能</li>
                    <li>NOSTA REGIのすべての機能</li>
                    <li>NOSTA SHOPのすべての機能</li>
                    <li>NOSTA MARKETのすべての機能</li>
                    <li>５店舗で使用可能</li>
                </ul>
                <p class="help">５店舗以上で導入をお考えいただいている場合はお問い合わせください</p>
                <p class="mt-3">詳細については各機能の紹介ページをご覧ください</p>
            </div>
            -->
        </div>
    </div>
    <div class="container my-4" id="model-case">
        <h3 class="has-text-centered my-6" style="font-size: min(8vw, 3rem)">NOSTAの活用例</h3>
        <div class="container box mx-3">
            <div class="is-size-6" style="color: #00517c"><b>CASE.1</b></div>
            <br />
            <div class="is-size-4">手軽に始めるデジタル化</div>
            <hr />
            <div class="columns has-text-centered is-hidden-mobile">
                <div class="column"><p>店舗のタブレットでお客様がチケット発券</p></div>
                <div class="column">
                    <p>お客様自身のスマートフォンから<br />呼び出し中の番号を確認</p>
                </div>
                <div class="column">
                    <p>番号が近くなったら<br />店舗のディスプレイで</p>
                </div>
                <div class="column"><p>お呼び出し</p></div>
            </div>
            <div class="columns is-hidden-mobile">
                <div class="column"><img src="{% static 'image/top/ticket/tablet.png' %}" /></div>
                <div class="column"><img src="{% static 'image/top/ticket/smartphone.png' %}" /></div>
                <div class="column"><img src="{% static 'image/top/ticket/monitor.png' %}" /></div>
                <div class="column"><img src="{% static 'image/top/ticket/people.png' %}" /></div>
            </div>
            <div class="columns has-text-centered is-hidden-tablet">
                <div class="column"><p>店舗のタブレットでお客様がチケット発券</p><hr><img src="{% static 'image/top/ticket/tablet.png' %}" /></div>
                <div class="column">
                    <p>お客様自身のスマートフォンから<br />呼び出し中の番号を確認<hr><img src="{% static 'image/top/ticket/smartphone.png' %}" /></p>
                </div>
                <div class="column">
                    <p>番号が近くなったら<br />店舗のディスプレイで<hr><img src="{% static 'image/top/ticket/monitor.png' %}" /></p>
                </div>
                <div class="column"><p>お呼び出し</p><hr><img src="{% static 'image/top/ticket/people.png' %}" /></div>
            </div>
        </div>
        <div class="container box mx-3">
            <div class="is-size-6" style="color: #00517c"><b>CASE.2</b></div>
            <br />
            <div class="is-size-4">すべてをNOSTAで</div>
            <hr />
            <div class="columns has-text-centered is-hidden-mobile">
                <div class="column"><p>NOSTA TICKETで整理券を発券</p></div>
                <div class="column">
                    <p>NOSTA REGIでお会計</p>
                </div>
                <div class="column">
                    <p>NOSTA SHOPでリアルタイムでチケットや販売状況を確認</p>
                </div>
                <div class="column"><p>NOSTA SHOPで商品や顧客の分析</p></div>
            </div>
            <div class="columns is-hidden-mobile">
                <div class="column"><img src="{% static 'image/top/ticket/tablet.png' %}" /></div>
                <div class="column"><img src="{% static 'image/top/ticket/regi.png' %}" /></div>
                <div class="column"><img src="{% static 'image/top/ticket/pc_with_people.png' %}" /></div>
                <div class="column"><img src="{% static 'image/top/ticket/analytics.png' %}" /></div>
            </div>
            <div class="columns has-text-centered  is-hidden-tablet">
                <div class="column"><p>NOSTA TICKETで整理券を発券</p><hr><img src="{% static 'image/top/ticket/tablet.png' %}" /></div>
                <div class="column">
                    <p>NOSTA REGIでお会計</p><hr><div class="column"><img src="{% static 'image/top/ticket/regi.png' %}" />
                </div>
                <div class="column">
                    <p>NOSTA SHOPでリアルタイムでチケットや販売状況を確認</p><hr><img src="{% static 'image/top/ticket/pc_with_people.png' %}" />
                </div>
                <div class="column"><p>NOSTA SHOPで商品や顧客の分析</p><hr><img src="{% static 'image/top/ticket/analytics.png' %}" /></div>
            </div>
        </div>
    </div>
    <div class="container my-4" id="support">
        <div class="box has-text-centered">
            <div class="has-text-centered" style="font-size: min(5vw, 1.5rem)">サポート</div>
            <hr />
            <p class="is-size-6">導入の際の質問からご利用中の疑問まで<b>24時間365日</b><c style="font-size: 10px">※１</c>サポート</p>
            <p class="help">お問い合わせ時期や送信内容により返信にお時間をいただく場合がございます</p>
            <div class="mt-3"></div>
            <a href="{% url 'about:faq' %}" class="button is-light is-info m-2">よくあるご質問はこちら</a>
            <a href="{% url 'about:contact' %}" class="button is-light is-info m-2">ご相談はこちら</a>
        </div>
    </div>
</section>
{% endblock %}