about/urls.py
from django.urls import re_path , include , path
from . import views

app_name = "about"
urlpatterns = [
    path('', views.home, name='home'),
    path('news', views.news, name='news'),
    path('service/ticket', views.s_ticket, name='se_ticket'),
    path('service/shop', views.s_shop, name='se_shop'),
    path('service/regi', views.s_regi, name='se_regi'),
    path('service/market', views.s_market, name='se_market'),
    path('support/guide', views.guide, name='guide'),
    path('support/contact', views.contact, name='contact'),
    path('support/faq', views.faq, name='faq'),
    path('support/about', views.about, name='about'),
    path('document/terms', views.terms, name='terms'),
    path('document/privacy', views.privacy, name='privacy'),
]

market/urls.py
from django.urls import re_path , include , path
from . import views

app_name = "market"
urlpatterns = [
    path('<str:shopCODE>/', views.market, name='index'),
    #path('<str:shopCODE>/mypage', views.market, name='mypage'),
]

nosta/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.contrib.auth import views as auth_views
from django.views.static import serve 
from django.conf import settings
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_control

urlpatterns = [
    path('system/admin/', admin.site.urls),
    path('', include('top.urls')),
    path('shop/', include('shop.urls')),
    path('app/', include('userapp.urls')),
    path('market/', include('market.urls')),
    path('regi/', include('regi.urls')),
    path('ticket/', include('ticket.urls')),
    path('auth/', include('appauth.urls')),
    path('news/',include('news.urls')),
    path('about/', include('about.urls')),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('accounts/password_change_form/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change_form'),
    path('accounts/password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_finish.html'), name='password_change_done'),
    path('accounts/password_reset_form/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),    # 追加
    path('accounts/password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_mail_done.html'), name='password_reset_done'),    # 追加
    path('accounts/password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirmation.html'), name='password_reset_confirm'),    # 追加
    path('accounts/password_reset_finish/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_finish.html'), name='password_reset_complete'),    # 追加
]

regi/urls.py
from django.urls import re_path , include , path
from . import views

app_name = "regi"
urlpatterns = [
    path('<str:shopCODE>', views.index, name='index'),
    path('app/<str:shopCODE>', views.app, name='app')
]

shop/urls.py
from django.urls import re_path , include , path
from . import views

app_name = "shop"
urlpatterns = [
    path('register/', views.register, name='register'),
    path('console/dashboard/<str:shopCODE>', views.dashboard, name='dashboard'),
    path('console/analytics/<str:shopCODE>', views.analytics, name='analytics'),
    path('console/members/<str:shopCODE>', views.members, name='members'),
    path('console/settings/<str:shopCODE>', views.settings, name='settings'),
    path('console/profile/<str:shopCODE>', views.profile, name='profile'),
    path('console/market/<str:shopCODE>', views.market, name='market'),
    path('console/product/<str:shopCODE>', views.product, name='product'),
    path('console/order/<str:shopCODE>', views.order, name='order'),
]

ticket/urls.py
from django.urls import re_path , include , path
from django.contrib.auth import views as auth_views
from . import views

app_name ="ticket"
urlpatterns = [
    path('console/dashboard/<str:shopCODE>', views.dashboard, name='dashboard'),
    path('console/customers/<str:shopCODE>', views.customers, name='customers'),
    path('console/settings/<str:shopCODE>', views.shop, name='shop'),
    path('view/<str:shopCODE>', views.customerview, name='client_external'),
    path('view/internal/<str:shopCODE>', views.shopview, name='client_internal'),
    path('reception/internal/<str:shopCODE>', views.reception_internal, name='reception_internal'),
    path('system/ajax',views.system_ajax,name='ajax')
]

top/urls.py
from django.urls import re_path , include , path
from . import views

app_name = "top"
urlpatterns = [
    path('', views.top, name='index'),
    ## Search is not view but also api.
    path('/search',views.search,name="search")
]

ticket/views.py
from django.shortcuts import render, redirect , reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from db.models import *
from django.db.models import *
import datetime as dt 
import pytz
import json

from module.user_auth import *

def consolo_access(request,shopCODE,authtype=None):
    shop = Shop.objects.get(code=shopCODE)
    if authtype:
        if user_permission_auth(request,shopCODE,"editor") == "allow":
            return True,shop
        else:
            return False,"dummy"
    if user_permission_auth(request,shopCODE,"editor") == "allow": 
        formatted = get_dayformat()
        tickets = Ticket.objects.all().filter(Q(shop=shop) & Q(day=formatted)& Q(shop=shop)).count()
        tickets_already = Ticket.objects.all().filter((Q(status="Canceled") | Q(status="Skipped")| Q(status="Called"))& Q(day=formatted)& Q(shop=shop))
        tickets_calling = Ticket.objects.all().filter(Q(status="Calling") & Q(day=formatted)& Q(shop=shop))
        tickets_yet = Ticket.objects.all().filter(Q(status="Waiting")& Q(day=formatted)& Q(shop=shop))
        return shop,tickets,tickets_already,tickets_calling,tickets_yet,formatted
    else:
        return "bad","dummy","dummy","dummy","dummy","dummy"


@login_required
def dashboard(request,shopCODE):
    shop,tickets,tickets_already,tickets_calling,tickets_yet,formatted = consolo_access(request,shopCODE)
    if shop == "bad":
        return redirect('home')

    news = News.objects.all().filter(Q(channel="ticket-console") | Q(channel="all")).order_by('created_at').reverse()[:3]
    # 来店者合計を計算
    result = Ticket.objects.filter(Q(day=formatted)&Q(shop=shop)).aggregate(sum=models.Sum('people'))
    peoplesum = result["sum"]
    result = Ticket.objects.filter(Q(shop=shop)).aggregate(sum=models.Sum('people'))
    allsum = result["sum"]
    return render(request, 'ticket/console/dashboard.html',{
        'shop':shop,
        'news':news,
        'tickets':tickets,
        'tickets_already':tickets_already,
        'tickets_calling':tickets_calling,
        'tickets_yet':tickets_yet,
        'peoplesum':peoplesum,
        'allsum':allsum,
        'tickets_callingAndalready':tickets_calling.count() + tickets_already.count()
    })

@login_required
def customers(request,shopCODE):
    shop,tickets,tickets_already,tickets_calling,tickets_yet,formatted = consolo_access(request,shopCODE)
    return render(request, 'ticket/console/customers.html',{
        'shop':shop,
        'tickets':tickets,
        'tickets_already':tickets_already,
        'tickets_yet':tickets_yet,
        'tickets_calling':tickets_calling
    })

@login_required
def shop(request,shopCODE):
    shop = Shop.objects.get(code=shopCODE)
    if user_permission_auth(request,shopCODE,"editor") == "allow":
        cstype_list = CStype.objects.all().filter(shop=shop)
        return render(request, 'ticket/console/shop.html',{'shop':shop,'cstype_list':cstype_list})
    else:
        return redirect('home')


@login_required
def reception_internal(request,shopCODE):
    shop = Shop.objects.get(code=shopCODE)
    cstype_list = CStype.objects.all().filter(shop=shop)
    if user_permission_auth(request,shopCODE,"operator") == "allow":
        return render(request, 'ticket/reception.html',{'shop':shop,'cstype_list':cstype_list})
    else:
        return redirect('home')

@csrf_exempt
def system_ajax(request):
    """
    悪意あるコードで店舗ID捏造して不正アクセスされる可能性あるけど共通認証モジュールに対応してない(URLにshopCODEを含んでない)から対応見送ります（2023/08/10）
    if user_permission_auth(request,shopCODE,"operator") == "allow":
        pass
    else:
        return
    """
    match request.POST["command"]:
        case 'create_tickets':
            formatted = get_dayformat()
            shop = Shop.objects.get(id=request.POST["shopID"])
            latestnumber = Ticket.objects.all().filter(Q(shop = shop) & Q(day=formatted)).aggregate(Max('number'))["number__max"]
            Ticket.objects.all().filter(Q(shop = shop) & Q(day=formatted))
            if latestnumber == None:
                latestnumber = 0
            ticket = Ticket.objects.create(
                number=latestnumber + 1,
                shop=shop,
                people=request.POST["people"],
                cstype=request.POST["cstype"],
                status="Waiting",
                location=request.POST["provider"],
                day=str(formatted),
                waiting=0
            )
            data = {
                "ticket_number":ticket.number,
                "ticket_created":str(ticket.created_at.strftime("%Y/%m/%d %H:%M:%S"))
            }
            json_str = json.dumps(data, ensure_ascii=False, indent=2)
            return HttpResponse(json_str)
        
        case 'called_ticket':
            tid = request.POST["tid"]
            jst = pytz.timezone('Asia/Tokyo')
            now = dt.datetime.now(jst)
            ticket = Ticket.objects.get(id=tid)
            ticket.status = "Called"
            ticket.finished_at = now
            ticket.save()
            return HttpResponse("OK!")
        
        case 'calling_ticket':
            tid = request.POST["tid"]
            ticket = Ticket.objects.get(id=tid)
            ticket.status = "Calling"
            ticket.save()
            return HttpResponse("OK!")

        case 'skipped_ticket':
            tid = request.POST["tid"]
            jst = pytz.timezone('Asia/Tokyo')
            now = dt.datetime.now(jst)
            ticket = Ticket.objects.get(id=tid)
            ticket.status = "Skipped"
            ticket.finished_at = now
            ticket.save()
            return HttpResponse("OK!")

        case 'canceled_ticket':
            tid = request.POST["tid"]
            jst = pytz.timezone('Asia/Tokyo')
            now = dt.datetime.now(jst)
            ticket = Ticket.objects.get(id=tid)
            ticket.status = "Canceled"
            ticket.finished_at = now
            ticket.save()
            return HttpResponse("OK!")
    
        case 'setting':
            tf,shop = consolo_access(request,request.POST["shopcode"],"AUTH")
            if tf == True:
                shop.name = request.POST["shop_name"]
                shop.ucc_ticket = request.POST["shop_message"]
                shop.people_min = request.POST["min_number"]
                shop.people_max = request.POST["max_number"]
                #shop.online_ticket = request.POST["reception_online"]
                #shop.online_auth = request.POST["userauth"]
                shop.email_message = request.POST["email_message"]
                shop.save()
                return HttpResponse("OK!")

            else:
                return

def customerview(request,shopCODE):
    shop = Shop.objects.get(code=shopCODE)
    dayformat = get_dayformat()
    tickets_calling = Ticket.objects.all().filter(Q(status="Calling") & Q(day=dayformat)& Q(shop=shop))
    return render(request,'ticket/customer/all_view.html',{'shop':shop,'tickets_calling':tickets_calling})

def shopview(request,shopCODE):
    shop = Shop.objects.get(code=shopCODE)
    dayformat = get_dayformat()
    tickets_calling = Ticket.objects.all().filter(Q(status="Calling") & Q(day=dayformat)& Q(shop=shop))
    tickets_waiting = Ticket.objects.all().filter(Q(status="Waiting") & Q(day=dayformat)& Q(shop=shop))
    return render(request,'ticket/customer/shop_view.html',{'shop':shop,'tickets_calling':tickets_calling,'tickets_waiting':tickets_waiting})

templates/ticket/accounthome.html
{% extends 'auth_base.html' %} {% block content %}{% load static %}
<div style="min-width: 40vm">
    <strong>ようこそ {{ user.username }} さん</strong>
    <div class="is-size-3">店舗を選択してください</div>
    <div class="mt-6">
        <ul>
            {% for shop in shops %}
            <hr />
            <li><a href="{% url 'ticket:dashboard' shop.code %}" class="is-fullwidth my-2 arrow" style="width: 90%">{{ shop.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <hr />
    <a href="{% url 'shop:register' %}" class="button is-info is-light is-fullwidth">新規作成</a>
</div>
{% endblock %}

templates/ticket/console_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <title>管理コンソール</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="NOSTAチケットサービス管理画面ではチケットの設定、呼び出し、確認が簡単に行えます。" />
        <meta name="theme-color" content="#00517c" />
        <link rel="icon" href="{% static 'image/favicon.ico' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css" />
        <link rel="stylesheet" href="{% static 'css/console.css' %}" />
        <!-- Our project just needs Font Awesome Free's Solid and Brand files -->
        <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/charts.css/dist/charts.min.css" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag() {
                dataLayer.push(arguments);
            }
            gtag('js', new Date());

            gtag('config', 'G-KNEMN3XWCG');
        </script>
        <link rel="manifest" href="{% static 'manifest_shop_app.json' %}" />
        <script>
            if ('serviceWorker' in navigator) {
                window.addEventListener('load', function () {
                    navigator.serviceWorker.register('{% static "sw.js" %}').then(
                        function (registration) {
                            // Registration was successful
                            console.log('ServiceWorker registration successful with scope: ', registration.scope);
                        },
                        function (err) {
                            // registration failed :(
                            console.log('ServiceWorker registration failed: ', err);
                        }
                    );
                });
            }
        </script>
    </head>
    <body>
        <section class="columns is-gapless is-hidden-mobile" style="min-height: 100vh; overflow: auto">
            <section class="column is-2" style="background-color: #eaf4fc">
                <nav class="navbar" role="navigation" aria-label="main navigation" style="background-color: #eaf4fc">
                    <div class="navbar-brand" style="margin: auto; display: block;">
                        <img src="{% static 'image/logo_ticket.png' %}" class="navbar-item" style="max-height: 10rem;"  alt="ロゴ" />
                    </div>
                </nav>
                <div class="container is-side sidebar m-2">
                    <aside class="menu">
                        <div style="display: flex; width: 100%; flex-wrap: wrap;"><strong>{{ shop.name }}</strong></div>
                        <p class="menu-label">General</p>
                        <ul class="menu-list">
                            <li><a href="{% url 'ticket:dashboard' shop.code %}" id="side_dashboard" class="">Dashboard</a></li>
                            <li><a href="{% url 'ticket:customers' shop.code %}">Customers</a></li>
                        </ul>
                        <p class="menu-label">Administration</p>
                        <ul class="menu-list">
                            <li><a href="{% url 'ticket:shop' shop.code %}">Settings</a></li>
                        </ul>
                        <p class="menu-label">display</p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'ticket:reception_internal' shop.code %}" target="_blank">
                                    チケット発券
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'ticket:client_internal' shop.code %}" target="_blank">
                                    呼び出し表示
                                </a>
                            </li>
                        </ul>
                        <p class="menu-label">client</p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'ticket:client_external' shop.code %}" target="_blank">
                                    呼び出し状況
                            </li>
                        </ul>
                        <p class="menu-label">Link</p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'about:home' %}">
                                    <span class="icon-text">
                                        <span class="icon has-text-info">
                                            <i class="fa-solid fa-arrow-up-right-from-square"></i>
                                        </span>
                                        <span>NOSTA TOP</span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'shop:dashboard' shop.code %}">
                                    <span class="icon-text">
                                        <span class="icon has-text-info">
                                            <i class="fa-solid fa-arrow-up-right-from-square"></i>
                                        </span>
                                        <span>NOSTA SHOP</span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'regi:index' shop.code %}">
                                    <span class="icon-text">
                                        <span class="icon has-text-info">
                                            <i class="fa-solid fa-arrow-up-right-from-square"></i>
                                        </span>
                                        <span>NOSTA REGI</span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'market:index' shop.code %}">
                                    <span class="icon-text">
                                        <span class="icon has-text-info">
                                            <i class="fa-solid fa-arrow-up-right-from-square"></i>
                                        </span>
                                        <span>NOSTA MARKET</span>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a>
                                    <span class="icon-text">
                                        <span class="icon has-text-info">
                                            <i class="fa-solid fa-arrow-up-right-from-square"></i>
                                        </span>
                                        <span>ABOUT </span>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="menu-label">ACCOUNT</p>
                        <ul class="menu-list">
                            <li><a class="navbar-item" href="{% url 'about:contact' %}"> Contact </a></li>
                            <li><a class="navbar-item" href="{% url 'home' %}"> Home </a></li>
                            <li><a class="navbar-item" href="{% url 'logout' %}"> Logout </a></li>
                        </ul>
                    </aside>
                </div>
            </section>
            <section class="column is-10" style="overflow-y: auto; overflow-x: hidden;">{% block content %}{% endblock %}</section>
        </section>
        <div class="is-hidden-tablet">
            <section class="hero is-large is-danger" style="background-color: #00517c">
                <div class="hero-body">
                    <b class="has-text-centered title is-size-5">お使いの端末ではご利用頂けません</b>
                    <p class="has-text-centered title is-size-6">パソコンやタブレットなどからご利用ください</p>
                    <div class="columns my-6">
                        <div class="column has-text-centered"><a class="button is-light" style="width: 80vw" href="{% url 'service' shop.code %}">サービストップ</a></div>
                    </div>
                </div>
            </section>
        </div>
    </body>
</html>