about/urls.py
from django.urls import re_path , include , path
from . import views

app_name = "about"
urlpatterns = [
    path('', views.home, name='home'),
    path('news', views.news, name='news'),
    path('service/ticket', views.s_ticket, name='se_ticket'),
    path('service/shop', views.s_shop, name='se_shop'),
    path('service/regi', views.s_regi, name='se_regi'),
    path('service/market', views.s_market, name='se_market'),
    path('support/guide', views.guide, name='guide'),
    path('support/contact', views.contact, name='contact'),
    path('support/faq', views.faq, name='faq'),
    path('support/about', views.about, name='about'),
    path('document/terms', views.terms, name='terms'),
    path('document/privacy', views.privacy, name='privacy'),
]

nosta/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.contrib.auth import views as auth_views
from django.views.static import serve 
from django.conf import settings
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_control

urlpatterns = [
    path('system/admin/', admin.site.urls),
    path('', include('top.urls')),
    path('shop/', include('shop.urls')),
    path('app/', include('userapp.urls')),
    path('market/', include('market.urls')),
    path('regi/', include('regi.urls')),
    path('ticket/', include('ticket.urls')),
    path('auth/', include('appauth.urls')),
    path('news/',include('news.urls')),
    path('about/', include('about.urls')),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('accounts/password_change_form/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change_form'),
    path('accounts/password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_finish.html'), name='password_change_done'),
    path('accounts/password_reset_form/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),    # 追加
    path('accounts/password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_mail_done.html'), name='password_reset_done'),    # 追加
    path('accounts/password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirmation.html'), name='password_reset_confirm'),    # 追加
    path('accounts/password_reset_finish/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_finish.html'), name='password_reset_complete'),    # 追加
]

top/urls.py
from django.urls import re_path , include , path
from . import views

app_name = "top"
urlpatterns = [
    path('', views.top, name='index'),
    ## Search is not view but also api.
    path('/search',views.search,name="search")
]

top/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from db.models import *
from django.db.models import *
from django.db.models.functions import *
from django.template.loader import render_to_string

# Create your views here.
def top(requests):
    shops = Shop.objects.filter(market_active=True).annotate(fav=Count('favorites')).order_by('fav')
    return render(requests,'top/index.html',{'shops':shops})
def search(requests):
    key = requests.POST["key"]
    shops = Shop.objects.filter(Q(market_active=True)&(Q(name__icontains=key)|Q(description__icontains=key))).annotate(fav=Count('favorites')).order_by('fav')
    data = render_to_string('top/search.html',{
        'shops':shops
    })
    return HttpResponse(data)

templates/top/support/contact.html
{% extends 'page_base.html' %}{% load static %}{% block content %}
<section>
    <link type="stylesheet" src="{% static 'css/contact.css' %}" />
    <div class="hero">
        <div class="hero-body has-text-centered">
            <p class="title">お問い合わせ</p>
        </div>
    </div>
    <form class="Form" action="{% url 'top:contact' %}" method="POST">
        {% csrf_token %}
        <div class="Form-Item">
            <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>会社/団体名</p>
            <input type="text" class="Form-Item-Input input" name="org" placeholder="例）株式会社NOSTA" />
        </div>
        <div class="Form-Item">
            <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>氏名</p>
            <input type="text" class="Form-Item-Input input" name="name" placeholder="例）野須 太一" />
        </div>
        <div class="Form-Item">
            <p class="Form-Item-Label"><span class="Form-Item-Label-Required">必須</span>メールアドレス</p>
            <input type="email" class="Form-Item-Input input" name="email" placeholder="例）example@gmail.com" />
        </div>
        <div class="Form-Item">
            <p class="Form-Item-Label isMsg"><span class="Form-Item-Label-Required">必須</span>お問い合わせ内容</p>
            <textarea class="Form-Item-Textarea input" name="content"></textarea>
        </div>
        <div class="Form-Item" style="display: inline-block">
            <a href="{% url 'top:privacy' %}">こちら</a>をお読みになり、NOSTA運営チームプライバシーポリシー(個人情報保護方針)についてご理解の上送信してください。
            送信内容は自動返信メールでお届けします。 メールが届かない場合は以下の内容をご確認の上、再度お問い合わせください。
            <br />
            <ul>
                <li>・ご入力いただいたメールアドレスが間違っていないか</li>
                <li>・メール受信制限機能で@nosta.prasic-plus.comもしくは@gmail.com制限していないか</li>
            </ul>
        </div>
        <div class="has-text-centered">
            <input type="submit" class="button my-6 is-outlined is-info has-text-centered" value="上記のことに同意して送信する" />
        </div>
    </form>
</section>
{% endblock %}

templates/top/support/faq.html
{% extends 'page_base.html' %}{% load static %}{% block content %}
<div style="height: 30px"></div>
<nav class="breadcrumb mx-3 my-1" aria-label="breadcrumbs">
    <ul>
        <li><a class="is-size-6 mx-1" href="{% url 'top:home' %}" aria-current="page" style="color: #00517c">トップ</a></li>
        <li><a class="is-size-6 mx-1" href="#" aria-current="page" style="color: #323232">よくあるご質問</a></li>
    </ul>
</nav>
<section class="columns p-4 m-0" style="min-height: 50vh">
    <!-- ここにサイドバーの部品を配置 -->
    <div class="submenu column is-4" style="max-width: 300px">
        <aside class="box menu">
            <section>
                <div class="">
                    <div class="has-text-centered">
                        <p class="title">FAQ</p>
                        <p>解決しない場合は<br />お問い合わせください</p>
                        <a class="button is-info is-light mt-3" href="{% url 'top:contact' %}">お問い合わせ</a>
                    </div>
                </div>
            </section>
            <p class="menu-label">一般</p>
            <ul class="menu-list">
                {% if general.count != 0 %}
                <li><a href="#General">NOSTA全般</a></li>
                {% endif %}
            </ul>
            <p class="menu-label">サービス</p>
            <ul class="menu-list">
                {% if ticket.count != 0 %}
                <li>
                    <a href="#Ticket">TICKET</a>
                </li>
                {% endif %} {% if shop.count != 0 %}
                <li>
                    <a href="#Shop">SHOP</a>
                </li>
                {% endif %} {% if regi.count != 0 %}
                <li>
                    <a href="#Regi">REGI</a>
                </li>
                {% endif %} {% if market.count != 0 %}
                <li>
                    <a href="#Market">MARKET</a>
                </li>
                {% endif %}
            </ul>
            <p class="menu-label">その他</p>
            {% if other.count != 0 %}
            <ul class="menu-list">
                <li><a href="#Other">その他</a></li>
            </ul>
            {% endif %}
        </aside>
    </div>
    <div class="column is-8">
        <!-- General -->
        <div class="container m-3" id="General">
            {% for content in general %}
            <div class="container box">
                <h1 class="is-size-5">Q. {{ content.title }}</h1>
                <p class="m-3">{{ content.question | linebreaksbr }}</p>
                <hr style="background-color: #00517c" />
                <h3><strong>回答</strong></h3>
                <p>{{ content.answer | linebreaksbr }}</p>
                <hr />
                <p>作成日: {{ content.created_at | date:"Y/m/d" }}</p>
                <p>更新日: {{ content.updated_at | date:"Y/m/d" }}</p>
            </div>
            {% endfor %}
        </div>
        <div class="container m-3" id="Ticket">
            {% for content in ticket %}
            <div class="container box">
                <h1 class="is-size-5">Q. {{ content.title }}</h1>
                <p class="m-3">{{ content.question | linebreaksbr }}</p>
                <hr style="background-color: #00517c" />
                <h3><strong>回答</strong></h3>
                <p>{{ content.answer | linebreaksbr }}</p>
                <hr />
                <p>作成日: {{ content.created_at | date:"Y/m/d" }}</p>
                <p>更新日: {{ content.updated_at | date:"Y/m/d" }}</p>
            </div>
            {% endfor %}
        </div>
        <div class="container m-3" id="Shop">
            {% for content in shop %}
            <div class="container box">
                <h1 class="is-size-5">Q. {{ content.title }}</h1>
                <p class="m-3">{{ content.question | linebreaksbr}}</p>
                <hr style="background-color: #00517c" />
                <h3><strong>回答</strong></h3>
                <p>{{ content.answer | linebreaksbr }}</p>
                <hr />
                <p>作成日: {{ content.created_at | date:"Y/m/d" }}</p>
                <p>更新日: {{ content.updated_at | date:"Y/m/d" }}</p>
            </div>
            {% endfor %}
        </div>
        <div class="container m-3" id="REGI">
            {% for content in regi %}
            <div class="container box">
                <h1 class="is-size-5">Q. {{ content.title }}</h1>
                <p class="m-3">{{ content.question | linebreaksbr }}</p>
                <hr style="background-color: #00517c" />
                <h3><strong>回答</strong></h3>
                <p>{{ content.answer | linebreaksbr }}</p>
                <hr />
                <p>作成日: {{ content.created_at | date:"Y/m/d" }}</p>
                <p>更新日: {{ content.updated_at | date:"Y/m/d" }}</p>
            </div>
            {% endfor %}
        </div>
        <div class="container m-3" id="Market">
            {% for content in market %}
            <div class="container box">
                <h1 class="is-size-5">Q. {{ content.title }}</h1>
                <p class="m-3">{{ content.question | linebreaksbr }}</p>
                <hr style="background-color: #00517c" />
                <h3><strong>回答</strong></h3>
                <p>{{ content.answer | linebreaksbr }}</p>
                <hr />
                <p>作成日: {{ content.created_at | date:"Y/m/d" }}</p>
                <p>更新日: {{ content.updated_at | date:"Y/m/d" }}</p>
            </div>
            {% endfor %}
        </div>
        <div class="container m-3" id="Other">
            {% for content in other %}
            <div class="container box">
                <h1 class="is-size-5">Q. {{ content.title }}</h1>
                <p class="m-3">{{ content.question | linebreaksbr }}</p>
                <hr style="background-color: #00517c" />
                <h3><strong>回答</strong></h3>
                <p>{{ content.answer | linebreaksbr }}</p>
                <hr />
                <p>作成日: {{ content.created_at | date:"Y/m/d" }}</p>
                <p>更新日: {{ content.updated_at | date:"Y/m/d" }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}